spring:
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8181
