spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT}

service:
  payment:
    url: ${SERVICE_PAYMENT_URL}
  user:
    url: ${SERVICE_USER_URL}

file:
  upload:
    path: ${FILE_UPLOAD_PATH}
    allowed-types: ${FILE_UPLOAD_ALLOWED_TYPES:}